<?php

$__luhn__ = 'Luhn algorithm';
$__yes__  = 'Yes';
$__no__   = 'No';

return [
	[
		'name'      => 'American Express',
		'id-range'  => [ 34, 37 ],
		'status'    => $__yes__,
		'length'    => [ 15 ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'Bankcard',
		'id-range'  => [ 5610, [ 560221, 560225 ] ],
		'status'    => $__no__,
		'length'    => [ 16 ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'China T-Union',
		'id-range'  => [ 31 ],
		'status'    => $__yes__,
		'length'    => [ 19 ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'China UnionPay',
		'id-range'  => [ 62 ],
		'status'    => $__yes__,
		'length'    => [ [ 16, 19 ] ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'Diners Club enRoute',
		'id-range'  => [],
		'status'    => $__yes__,
		'length'    => [ 15 ],
		'validator' => 'No Validation',
	],
	[
		'name'      => 'Diners Club International',
		'id-range'  => [ 30, 36, 38, 39 ],
		'status'    => $__yes__,
		'length'    => [ [ 14, 19 ] ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'Diners Club United States & Canada',
		'id-range'  => [ 55 ],
		'status'    => $__yes__,
		'length'    => [ 16 ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'Discover Card',
		'id-range'  => [ 6011, [ 644, 649 ], 65 ],
		'status'    => $__yes__,
		'length'    => [ [ 16, 19 ] ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'Discover Card',
		'id-range'  => [ [ 622126, 622925 ] ],
		'status'    => $__yes__,
		'length'    => [ [ 16, 19 ] ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'UkrCart',
		'id-range'  => [ [ 60400100, 60420099 ] ],
		'status'    => $__yes__,
		'length'    => [ [ 16, 19 ] ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'RuPay',
		'id-range'  => [ 60, 65, 81, 82, 508 ],
		'status'    => $__yes__,
		'length'    => [ 16 ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'RuPay',
		'id-range'  => [ 353, 356 ],
		'status'    => $__yes__,
		'length'    => [ 16 ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'InterPayment',
		'id-range'  => [ 636 ],
		'status'    => $__yes__,
		'length'    => [ [ 16, 19 ] ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'InstaPayment',
		'id-range'  => [ [ 637, 639 ] ],
		'status'    => $__yes__,
		'length'    => [ 16 ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'JCB',
		'id-range'  => [ [ 3528, 3589 ] ],
		'status'    => $__yes__,
		'length'    => [ [ 16, 19 ] ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'Laser',
		'id-range'  => [ 6304, 6706, 6771, 6709 ],
		'status'    => $__no__,
		'length'    => [ [ 16, 19 ] ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'Maestro UK',
		'id-range'  => [ 6759, 676770, 676774 ],
		'status'    => $__yes__,
		'length'    => [ [ 12, 19 ] ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'Maestro',
		'id-range'  => [ 5018, 5020, 5038, 5893, 6304, 6759, 6761, 6762, 6763 ],
		'status'    => $__yes__,
		'length'    => [ [ 12, 19 ] ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'Dankort',
		'id-range'  => [ 5019 ],
		'status'    => $__yes__,
		'length'    => [ 16 ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'Dankort',
		'id-range'  => [ 4571 ],
		'status'    => $__yes__,
		'length'    => [ 16 ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'Mir',
		'id-range'  => [ [ 2200, 2204 ] ],
		'status'    => $__yes__,
		'length'    => [ [ 16, 19 ] ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'BORICA',
		'id-range'  => [ 2205 ],
		'status'    => $__yes__,
		'length'    => [ 16 ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'NPS Pridnestrovie',
		'id-range'  => [ [ 6054740, 6054744 ] ],
		'status'    => $__no__,
		'length'    => [ 16 ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'Mastercard',
		'id-range'  => [ [ 2221, 2720 ] ],
		'status'    => $__yes__,
		'length'    => [ 16 ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'Mastercard',
		'id-range'  => [ [ 51, 55 ] ],
		'status'    => $__yes__,
		'length'    => [ 16 ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'Solo',
		'id-range'  => [ 6334, 6767 ],
		'status'    => $__no__,
		'length'    => [ 16, 18, 19 ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'Switch',
		'id-range'  => [ 4903, 4905, 4911, 4936, 564182, 633110, 6333, 6759 ],
		'status'    => $__no__,
		'length'    => [ 16, 18, 19 ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'Troy',
		'id-range'  => [ 65 ],
		'status'    => $__yes__,
		'length'    => [ 16 ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'Troy',
		'id-range'  => [ 9792 ],
		'status'    => $__yes__,
		'length'    => [ 16 ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'Visa',
		'id-range'  => [ 4 ],
		'status'    => $__yes__,
		'length'    => [ 13, 16, 19 ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'Visa Electron',
		'id-range'  => [ 4026, 417500, 4844, 4913, 4917 ],
		'status'    => $__yes__,
		'length'    => [ 16 ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'UATP',
		'id-range'  => [ 1 ],
		'status'    => $__yes__,
		'length'    => [ 15 ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'Verve',
		'id-range'  => [ [ 506099, 506198 ], [ 650002, 650027 ], [ 507865, 507964 ] ],
		'status'    => $__yes__,
		'length'    => [ 16, 18, 19 ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'LankaPay',
		'id-range'  => [ 357111 ],
		'status'    => $__yes__,
		'length'    => [ 16 ],
		'validator' => 'N/A',
	],
	[
		'name'      => 'Uzcard',
		'id-range'  => [ 8600, 5614 ],
		'status'    => $__yes__,
		'length'    => [ 16 ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'HUMO',
		'id-range'  => [ 9860 ],
		'status'    => $__yes__,
		'length'    => [ 16 ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'GPN',
		'id-range'  => [ 1946 ],
		'status'    => $__yes__,
		'length'    => [ 16, 18, 19 ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'GPN',
		'id-range'  => [ 50, 56, 58, [ 60, 63 ] ],
		'status'    => $__yes__,
		'length'    => [ 16, 18, 19 ],
		'validator' => $__luhn__,
	],
	[
		'name'      => 'Napas',
		'id-range'  => [ 9704 ],
		'status'    => $__yes__,
		'length'    => [ 16, 19 ],
		'validator' => 'Unknown',
	],
];
